spring:
  name: TabletaSheikah
  datasource:
    url: jdbc:postgresql://localhost:5432/hyrule_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2012
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.example.tabletasheikah: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
